version: '3.3'
    
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    volumes:
      - /docker/authelia:/config
    ports:
      - 9091:9091
    environment:
      - TZ=Europe/Warsaw
