version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    network_mode: "host"
    environment:
      - DNS_SERVER_DOMAIN=dns01.home 
    volumes:
      - /docker/technitium:/etc/dns
    restart: unless-stopped
